SHOW tables;

-- 프로필 사진 테이블
DROP TABLE IF EXISTS TBL_PROFILE_IMAGE;

CREATE TABLE IF NOT EXISTS TBL_PROFILE_IMAGE(
	PROFILE_IMAGE_NO int PRIMARY KEY AUTO_INCREMENT,
	PROFILE_IMAGE_ORIGINAL_NAME varchar(255) NOT NULL,
	PROFILE_IMAGE_CHANGED_NAME varchar(255) NOT NULL,
	PROFILE_IMAGE_EXT varchar(10) NOT NULL,
	PROFILE_IMAGE_PATH varchar(255) NOT NULL,
	PROFILE_IMAGE_REGIST_DATE date NOT NULL,
	PROFILE_IMAGE_UPDATE_DATE date
	)ENGINE=innodb;

-- 회원 정보 테이블
DROP TABLE IF EXISTS TBL_USER;

CREATE TABLE IF NOT EXISTS TBL_USER(
	USER_NO int PRIMARY KEY AUTO_INCREMENT,
	USER_EMAIL varchar(255) NOT NULL,
	USER_PASSWORD varchar(12) NOT NULL,
	USER_NICKNAME varchar(50) NOT NULL,
	USER_PHONE varchar(15) NOT NULL,
	USER_SNS varchar(10),
	USER_STATUS varchar(10) NOT NULL DEFAULT 'active',
	USER_AUTH varchar(10) NOT NULL,
	USER_REGIST_DATE date NOT NULL,
	USER_UPDATE_DATE date,
	PROFILE_IMAGE_NO int,
	FOREIGN KEY(PROFILE_IMAGE_NO) REFERENCES TBL_PROFILE_IMAGE(PROFILE_IMAGE_NO)	
	)ENGINE=innodb;

-- 블랙 리스트  테이블
DROP TABLE IF NOT EXISTS TBL_BLACKLIST(
	BLACK_NO int PRIMARY KEY AUTO_INCREMENT,
	USER_NO int NOT NULL,
	BLACK_REASON varchar(500) NOT NULL,
	